# Generated by Django 3.1.1 on 2020-09-22 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('level', models.CharField(max_length=100)),
                ('correct_ans', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('no_question_solved', models.IntegerField(default=0)),
                ('current_score', models.IntegerField(default=0)),
                ('question_attempted', models.TextField()),
                ('current_ques_id', models.IntegerField(default=0)),
                ('user_logout', models.IntegerField(default=0)),
                ('decision', models.IntegerField(default=0)),
                ('login_time', models.DateTimeField(max_length=100, null=True)),
                ('logout_time', models.DateTimeField(max_length=100, null=True)),
                ('predicted_logout_time', models.DateTimeField(max_length=100, null=True)),
                ('category', models.CharField(max_length=10)),
                ('user', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_1', models.IntegerField(default=-1)),
                ('attempt_2', models.IntegerField(default=-1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
