# Generated by Django 3.1.1 on 2020-10-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_userprofile_emergency_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
