# Generated by Django 3.1.1 on 2020-10-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_userprofile_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hot_or_cold',
            field=models.IntegerField(default=0),
        ),
    ]
